apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ibox-pvc-demo
  namespace: demo
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-storageclass-demo
